name: book-search

services:
  database:
    type: postgres:16
    portforward: 54320
    creds:
      user: postgres
      password: postgres
      database: book_search
    config:
      database: config/postgres.conf

  pgadmin:
    type: compose
    app_mount: disabled
    services:
      image: dpage/pgadmin4:latest
      user: root
      command: /bin/sh -c "/entrypoint.sh"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_CONFIG_SERVER_MODE: 'False'
        PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      ports:
        - "5050:80"
      volumes:
        - pgadmin_data:/var/lib/pgadmin

  appserver:
    type: compose
    services:
      image: maven:3.9-eclipse-temurin-17
      command: tail -f /dev/null
      volumes:
        - .:/app
      working_dir: /app
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/book_search
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

tooling:
  mvn:
    service: appserver
    cmd: mvn
  
  java:
    service: appserver
    cmd: java
  
  spring-boot:
    service: appserver
    cmd: mvn spring-boot:run
    description: Run the Spring Boot application
  
  psql:
    service: database
    cmd: psql -U postgres book_search
    description: Connect to PostgreSQL via psql

volumes:
  pgadmin_data:
    driver: local

